// Code generated by "stringer -type PhoneModel"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[iPhone4-0]
	_ = x[iPhone5-1]
	_ = x[iPhone6-2]
	_ = x[iPhone7-3]
	_ = x[iPhone8-4]
	_ = x[iPhone10-5]
	_ = x[iPhone11-6]
	_ = x[iPhone12-7]
	_ = x[iPhone13-8]
}

const _PhoneModel_name = "iPhone4iPhone5iPhone6iPhone7iPhone8iPhone10iPhone11iPhone12iPhone13"

var _PhoneModel_index = [...]uint8{0, 7, 14, 21, 28, 35, 43, 51, 59, 67}

func (i PhoneModel) String() string {
	if i < 0 || i >= PhoneModel(len(_PhoneModel_index)-1) {
		return "PhoneModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhoneModel_name[_PhoneModel_index[i]:_PhoneModel_index[i+1]]
}
